"""Rename material to spirit_type

Revision ID: 1834717eeeb8
Revises: 53a275dd30fc
Create Date: 2024-11-25 20:53:27.847585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1834717eeeb8'
down_revision: Union[str, None] = '53a275dd30fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bottles', 'material', new_column_name='spirit_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bottles', 'spirit_type', new_column_name='material')
    # ### end Alembic commands ###
