"""Initial migration

Revision ID: 53a275dd30fc
Revises: 
Create Date: 2024-11-13 02:57:49.261875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a275dd30fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands adjusted for initial migration ###
    op.create_table(
        'bottles',
        sa.Column('id', sa.Integer, primary_key=True, index=True, nullable=False),
        sa.Column('name', sa.String, nullable=False),
        sa.Column('brand', sa.String, nullable=True),           # New field for brand
        sa.Column('flavor_profile', sa.String, nullable=True),  # New field for flavor profile
        sa.Column('material', sa.String, nullable=True),
        sa.Column('capacity_ml', sa.Integer, nullable=True),
    )
    op.create_index('ix_bottles_id', 'bottles', ['id'], unique=False)
    # ### end commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bottles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('brand', sa.VARCHAR(), nullable=True),
    sa.Column('flavor_profile', sa.VARCHAR(), nullable=True),
    sa.Column('material', sa.VARCHAR(), nullable=True),
    sa.Column('capacity_ml', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bottles_id', 'bottles', ['id'], unique=False)
    # ### end Alembic commands ###
